<?php
return [
    'admin/users' => ['controller' => 'AdminUser', 'action' => 'adminIndex', 'admin' => true],
    'admin/users/create' => ['controller' => 'AdminUser', 'action' => 'create', 'admin' => true],
    'admin/users/edit/{id}' => ['controller' => 'AdminUser', 'action' => 'edit', 'admin' => true],
    'admin/users/delete/{id}' => ['controller' => 'AdminUser', 'action' => 'delete', 'admin' => true],
    'admin/users/toggle-status/{id}' => ['controller' => 'AdminUser', 'action' => 'toggleStatus', 'admin' => true],
    'admin/users/manage-groups/{id}' => ['controller' => 'AdminUserGroup', 'action' => 'manageUserGroups', 'admin' => true],
    'admin/user-groups' => ['controller' => 'AdminUserGroup', 'action' => 'index', 'admin' => true],
    'admin/user-groups/create' => ['controller' => 'AdminUserGroup', 'action' => 'create', 'admin' => true],
    'admin/user-groups/edit/{id}' => ['controller' => 'AdminUserGroup', 'action' => 'edit', 'admin' => true],
    'admin/user-groups/delete/{id}' => ['controller' => 'AdminUserGroup', 'action' => 'delete', 'admin' => true],
    'admin/user-groups/permissions/{id}' => ['controller' => 'AdminUserGroup', 'action' => 'permissions', 'admin' => true],
    'admin/user-achievements' => ['controller' => 'AdminUserAchievement', 'action' => 'index', 'admin' => true],
    'admin/user-achievements/create' => ['controller' => 'AdminUserAchievement', 'action' => 'create', 'admin' => true],
    'admin/user-achievements/edit/{id}' => ['controller' => 'AdminUserAchievement', 'action' => 'edit', 'admin' => true],
    'admin/user-achievements/delete/{id}' => ['controller' => 'AdminUserAchievement', 'action' => 'delete', 'admin' => true],
    'admin/user-achievements/toggle/{id}' => ['controller' => 'AdminUserAchievement', 'action' => 'toggle', 'admin' => true],
    'admin/user-achievements/assign/{userId}' => ['controller' => 'AdminUserAchievement', 'action' => 'assign', 'admin' => true],
    'admin/user-achievements/unassign/{userId}/{achievementId}' => ['controller' => 'AdminUserAchievement', 'action' => 'unassign', 'admin' => true],
    'admin/users/quick-assign-achievement/{userId}' => ['controller' => 'AdminUserAchievement', 'action' => 'quickAssign', 'admin' => true],
    'users' => ['controller' => 'User', 'action' => 'index'],
    'user/{id}' => ['controller' => 'User', 'action' => 'show'],
    'users/achievements' => ['controller' => 'User', 'action' => 'achievements'],
    'achievement/{id}' => ['controller' => 'User', 'action' => 'achievement'],
];